# Generated by Django 6.0 on 2025-12-19 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SegyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('original_file', models.FileField(upload_to='segy/', verbose_name='Исходный SEG-Y файл')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('sample_rate', models.IntegerField(verbose_name='Интервал дискретизации (микросек)')),
                ('num_samples', models.IntegerField(verbose_name='Количество отсчётов на трассу')),
                ('num_traces', models.IntegerField(verbose_name='Количество трасс')),
                ('trace_data', models.BinaryField(verbose_name='Матрица трасс (бинарные данные float32)')),
            ],
            options={
                'verbose_name': 'SEG-Y файл',
                'verbose_name_plural': 'SEG-Y файлы',
                'db_table': 'spectral_segy_files',
            },
        ),
        migrations.CreateModel(
            name='TraceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_number', models.IntegerField(verbose_name='Номер трассы в файле')),
                ('ffig', models.IntegerField(verbose_name='FFIG - Field File Identification Number')),
                ('rec_x', models.FloatField(verbose_name='RECX - X координата приёмника')),
                ('rec_y', models.FloatField(verbose_name='RECY - Y координата приёмника')),
                ('sou_x', models.FloatField(verbose_name='SOUX - X координата источника')),
                ('sou_y', models.FloatField(verbose_name='SOUY - Y координата источника')),
                ('offset', models.FloatField(verbose_name='Offset - расстояние приём-источник')),
                ('elevation', models.FloatField(verbose_name='Elevation - высота')),
                ('cdp_x', models.FloatField(verbose_name='CDPX - X координата CDP')),
                ('cdp_y', models.FloatField(verbose_name='CDPY - Y координата CDP')),
                ('cdp', models.IntegerField(verbose_name='CDP - Common Depth Point')),
                ('dt', models.IntegerField(verbose_name='DT - интервал дискретизации (микросек)')),
                ('segy_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='spectral_masw.segyfile', verbose_name='SEG-Y файл')),
            ],
            options={
                'verbose_name': 'Заголовок трассы',
                'verbose_name_plural': 'Заголовки трасс',
                'db_table': 'spectral_trace_headers',
                'indexes': [models.Index(fields=['segy_file', 'trace_number'], name='spectral_tr_segy_fi_b9c3e1_idx'), models.Index(fields=['cdp'], name='spectral_tr_cdp_0e40aa_idx'), models.Index(fields=['offset'], name='spectral_tr_offset_58a2f4_idx')],
            },
        ),
    ]
