# Generated by Django 6.0 on 2025-12-20 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_masw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Результат обработки', max_length=255, verbose_name='Название результата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('spectrogram_matrix', models.BinaryField(help_text='Сохраняется как pickle numpy.ndarray (float32)', verbose_name='Матрица спектрограммы')),
                ('extent_x_min', models.FloatField(verbose_name='Min X (слева)')),
                ('extent_x_max', models.FloatField(verbose_name='Max X (справа)')),
                ('extent_y_min', models.FloatField(verbose_name='Min Y (снизу)')),
                ('extent_y_max', models.FloatField(verbose_name='Max Y (сверху)')),
                ('curve_x_array', models.BinaryField(help_text='numpy.ndarray float32', verbose_name='Массив X координат кривой')),
                ('curve_y_array', models.BinaryField(help_text='numpy.ndarray float32', verbose_name='Массив Y координат кривой')),
                ('processing_notes', models.TextField(blank=True, verbose_name='Заметки об обработке')),
                ('neural_network_model', models.CharField(default='default_model', max_length=100, verbose_name='Используемая модель нейросети')),
                ('segy_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectral_results', to='spectral_masw.segyfile', verbose_name='Исходный SEG-Y файл')),
            ],
            options={
                'verbose_name': 'Результат обработки спектрограммы',
                'verbose_name_plural': 'Результаты обработки спектрограмм',
                'db_table': 'spectral_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
