# Generated by Django 6.0 on 2025-12-20 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_masw', '0002_spectralresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segyfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spectralresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='spectralresult',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='segyfile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='segyfile',
            name='num_samples',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='segyfile',
            name='num_traces',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='segyfile',
            name='original_file',
            field=models.FileField(upload_to='segy/'),
        ),
        migrations.AlterField(
            model_name='segyfile',
            name='sample_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='segyfile',
            name='trace_data',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='segyfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='curve_x_array',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='curve_y_array',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='extent_x_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='extent_x_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='extent_y_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='extent_y_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='name',
            field=models.CharField(default='Результат спектрального анализа', max_length=255),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='neural_network_model',
            field=models.CharField(default='default_model', max_length=100),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='processing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='segy_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra', to='spectral_masw.segyfile'),
        ),
        migrations.AlterField(
            model_name='spectralresult',
            name='spectrogram_matrix',
            field=models.BinaryField(),
        ),
        migrations.AlterModelTable(
            name='segyfile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='spectralresult',
            table=None,
        ),
    ]
