# Generated by Django 6.0 on 2025-12-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_masw', '0003_alter_segyfile_options_alter_spectralresult_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectralresult',
            name='neural_network_model',
        ),
    ]
